#!/bin/sh

B='\033[0;34m'

projectname=$1

git clone https://github.com/goravel/goravel ./$projectname
rm -rf $projectname/.git

cd $projectname

echo "${B}Goravel is being installed, this might take a while..."

go mod tidy

cp .env.example .env

go run . artisan key:generate

echo "${B}Setup finished! Go and create something great :)"
