run:
  timeout: 5m
linters:
  enable:
    - gofmt
    - revive
    - exportloopref
    - gocritic
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/steebchen/prisma-client-go
